# Generated by Django 4.1.5 on 2023-04-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bags',
            old_name='bags_date',
            new_name='bag_date',
        ),
        migrations.RenameField(
            model_name='bags',
            old_name='port',
            new_name='bag_port',
        ),
    ]
