# Generated by Django 4.1.5 on 2023-04-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0002_rename_bags_date_bags_bag_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagDate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bag_date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BagHawbNo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hawb_no', models.CharField(max_length=20, unique=True)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BagNumber',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bag_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BagPort',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bag_port', models.CharField(max_length=10)),
                ('bag_date_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bags.bagdate')),
            ],
        ),
        migrations.DeleteModel(
            name='Bags',
        ),
        migrations.AddField(
            model_name='bagnumber',
            name='bag_port_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bags.bagport'),
        ),
        migrations.AddField(
            model_name='baghawbno',
            name='bag_number_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bags.bagnumber'),
        ),
    ]
