# Generated by Django 4.1.5 on 2023-04-09 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0003_bagdate_baghawbno_bagnumber_bagport_delete_bags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baghawbno',
            name='bag_number_id',
        ),
        migrations.RemoveField(
            model_name='bagnumber',
            name='bag_port_id',
        ),
        migrations.RemoveField(
            model_name='bagport',
            name='bag_date_id',
        ),
        migrations.AddField(
            model_name='baghawbno',
            name='bag_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bag_hawb_no', to='bags.bagnumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bagnumber',
            name='bag_port',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bag_number', to='bags.bagport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bagport',
            name='bag_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bag_port', to='bags.bagdate'),
            preserve_default=False,
        ),
    ]
