# Generated by Django 4.1.5 on 2023-04-10 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0004_remove_baghawbno_bag_number_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bagdate',
            old_name='bag_date',
            new_name='bagDate',
        ),
        migrations.RenameField(
            model_name='baghawbno',
            old_name='hawb_no',
            new_name='BagHawbNo',
        ),
        migrations.RenameField(
            model_name='bagnumber',
            old_name='bag_number',
            new_name='bagNumber',
        ),
        migrations.RenameField(
            model_name='bagport',
            old_name='bag_port',
            new_name='bagPort',
        ),
        migrations.RemoveField(
            model_name='baghawbno',
            name='bag_number',
        ),
        migrations.RemoveField(
            model_name='bagnumber',
            name='bag_port',
        ),
        migrations.RemoveField(
            model_name='bagport',
            name='bag_date',
        ),
        migrations.AddField(
            model_name='baghawbno',
            name='bagNumber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='baghawbno', to='bags.bagnumber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bagnumber',
            name='bagPort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bagnumber', to='bags.bagport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bagport',
            name='bagDate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bagport', to='bags.bagdate'),
            preserve_default=False,
        ),
    ]
