# Generated by Django 4.1.5 on 2023-04-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0005_rename_bag_date_bagdate_bagdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baghawbno',
            old_name='BagHawbNo',
            new_name='bagHawbNo',
        ),
    ]
