# Generated by Django 4.1.5 on 2023-04-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0006_rename_baghawbno_baghawbno_baghawbno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagdate',
            name='bagDate',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
