# Generated by Django 4.1.5 on 2023-04-26 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0007_alter_bagdate_bagdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagCheckHawbNo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bagHawbNo', models.CharField(max_length=20, unique=True)),
                ('bagPort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagcheckhawbno', to='bags.bagport')),
            ],
        ),
    ]
