# Generated by Django 4.1.5 on 2023-05-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0009_bagcheckhawbno_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagnumber',
            name='bagComment',
            field=models.CharField(default='', max_length=20),
        ),
    ]
