# Generated by Django 4.1.5 on 2023-05-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bags', '0010_bagnumber_bagcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagcheckhawbno',
            name='bagHawbNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='baghawbno',
            name='bagHawbNo',
            field=models.CharField(max_length=20),
        ),
    ]
