# Generated by Django 4.1.5 on 2023-02-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.IntegerField(default=0)),
                ('no', models.CharField(max_length=5)),
                ('hawbNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('shipper', models.TextField(default='')),
                ('consignee', models.TextField(default='')),
                ('item', models.TextField(default='')),
                ('ct', models.CharField(default='', max_length=5)),
                ('wt', models.CharField(default='', max_length=10)),
                ('value', models.CharField(default='', max_length=10)),
                ('attn', models.CharField(default='', max_length=100)),
                ('phoneNumber', models.CharField(default='', max_length=100)),
                ('pc', models.CharField(default='', max_length=100)),
                ('port', models.CharField(default='', max_length=100)),
                ('note', models.TextField(default='')),
                ('specialNote', models.TextField(default='')),
                ('charge1', models.CharField(default='', max_length=20)),
                ('charge2', models.CharField(default='', max_length=20)),
                ('team', models.CharField(default='', max_length=20)),
                ('address', models.TextField(default='')),
                ('insertDate', models.CharField(max_length=20)),
                ('modified', models.BooleanField(default=False)),
                ('scanned', models.BooleanField(default=False)),
                ('inspected', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('stepped', models.BooleanField(default=False)),
                ('sea', models.BooleanField(default=False)),
                ('together', models.BooleanField(default=False)),
                ('scanTimes', models.IntegerField(default=0)),
            ],
        ),
    ]
