# Generated by Django 4.1.5 on 2023-03-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifest', '0002_alter_manifest_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='exclude',
            field=models.BooleanField(default=False),
        ),
    ]
